### PR TITLE
Added scene changer spawn location parameter; fixed edge case bug with changing scenes

### PR DESCRIPTION
**Pull request by Deltt**
- Added globals autoload to keep track of variables between scenes, accessible globally with Globals.Instance.VARIABLE (currently only used to take the desired spawn location from a scene changer into the next scene and spawn the player there)

- Also fixed an edge case bug with changing scenes
(code was correct but an existing engine bug prevented loading between 2 scenes back and forth with the previous implementation, for more info see https://github.com/godotengine/godot/issues/77090)

As a side note, I haven't worked with git all that much so if I am doing something undesireable lemme know please, dunno if its common workflow to merge from main before contributing back or the other way around

### CODE REVIEW

**Comment by jonathandavidlewis** [comment]
@Deltt Do you know how to rebase your commits to not include the import files?
I was making a PR for those.

**Comment by jonathandavidlewis** [comment]
I made the PR for #33 which is adding the import files and moving the location of those images.

Because your branch also includes those changes, there will be a conflict.

Ideally when art is added, the import files are also added, but it didn't happen here, so we both ended up with the same changes.

**Comment by jonathandavidlewis** [comment]
If you want a hand with rebasing to remove the changes to the art files, let me know.

**Comment by jonathandavidlewis** [comment]
yeah, on your local git repo, ideally you have the following:

1. local "origin" is your fork.
2. local "upstream" is this org repo.

Before you make a PR, and frequently in general, use the following:

`git pull -r upstream main`

To pull in changes that are already in this org repo into your own work while keeping your work AFTER the existing work.

**Comment by Deltt** [comment]
I'll have to look into that later when I got the time, thanks for explaining!
Would it be fine if I just use the resolve conflicts feature for this with respect to the org-main branch and resync my fork, or is there something I'm missing with that?
Unfortunately I'm not familiar with rebasing or adept with the cli in general

**Comment by jonathandavidlewis** [comment]
@Deltt Using the in-browser feature makes a new commit, so it's not ideal. I can record myself resolving it locally and push up a branch you can see.

**Comment by Deltt** [comment]
That would be wonderful! If its not too inconvenient for you ofc, I don't know if other people are already working on the same stuff / more advanced stuff, didn't find anything regarding that in the project tasks

**Comment by jonathandavidlewis** [comment]
@Deltt You can take a look at #38 and let me know if it looks good to you.

**Comment by jonathandavidlewis** [comment]
I merged the work using the other branch.

**Pull request closed without merging**
