### PR TITLE
Respawn update

### PR DESCRIPTION
**Pull request by DeadRobotDev**
- Add transition.
- Fix camera movement still happening after fade in.

Finishes #20

### CODE REVIEW

**Comment by jonathandavidlewis** [comment]
@DeadRobotDev I like the design of having a movement transition tool. Very clever.

**Comment by jonathandavidlewis** [comment]
@DeadRobotDev Are you able to resolve the conflict here or would you prefer I do?

**Comment by jonathandavidlewis** [comment]
Just adding here to keep the discussion connected to the work.

From discord:
Do you think you could make a sample scene in project/tests/scenes/test_respawn (or something like that) that uses the mechanic?
It can just have  a  srcript at the root of the test scene that makes the respawn happen.

Otherwise, I can give it a go.

**Comment by jonathandavidlewis** [comment]
I tried it using R and it's working great! Nice job!

**Comment by DeadRobotDev** [comment]
From Discord:
Do we still want a sample scene, or is R suitable?

**Comment by jonathandavidlewis** [comment]
@DeadRobotDev Yeah, the benefit later is exactly that. It's a premade simple test case without a lot of other factors.

I was able to test it, so good enough for now.

**Pull request merged**
